name: projectdesk_recovery
description: ProjectDesk legacy recovery utility
publish_to: "none"
version: 1.4.0+14

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
